# Site settings
title: "ë„ë‘"
description: "í•­ìƒ ê²¸ì†í•¨ì€ ì²˜ìŒì²˜ëŸ¼ (Null do) ì‹¤ë ¥ì€ ë„ˆë“œì²˜ëŸ¼ (Nerd do) ğŸ”¥"
keyword: 'Chromium, Algorithm, Baekjoon, C++, Google'
url: 'https://0xd00d00.github.io' # your host

baseurl: ''

# Navigation links
nav:
  home: '/'
  wiki: '/wiki/root-index'
  tags: '/tags.html'
  archive: '/archive.html'

# [doodoo] if you append the page, write here.
#haha: '/'

# Footer
footer:
  since: 2021

# Author info
author: 'ë„ë‘'
nickname: 'ë„ë‘'
bio: "í•­ìƒ ê²¸ì†í•¨ì€ ì²˜ìŒì²˜ëŸ¼ (Null do) ì‹¤ë ¥ì€ ë„ˆë“œì²˜ëŸ¼ (Nerd do) ğŸ”¥"
avatar: '/assets/img/profile.png'

# Search
search: true

# Night mode
nightMode: false

# Comments
comments:
  disqus: false
  disqus_url: 'https://liaokeyu.disqus.com/embed.js'

mathjax: true

# Share
#social-share: true
#social-share-items: ['wechat', 'weibo', 'douban', 'twitter']

# theme color
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings
# url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  email: 'mailto:0xd00d00b@gmail.com'
  github: '//github.com/0xd00d00'

# Tags
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 6 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# RSS
RSS: false

# codepen user name
codepen_username: 0xd00d00

# permalink í•  ë•Œ, collections ê°€ ì•„ë‹ˆë¼ colelctionì„.
collections:
  wiki:
    output: true
    permalink: /:collection/:path/

# Permalink
# See: https://github.com/kaeyleo/jekyll-theme-H2O/issues/35
permalink: /:year/:month/:day/:title.html

# ëŒ“ê¸€ ê¸°ëŠ¥
giscus:
  repo: 0xd00d00/giscus-blog-comment
  repo-id: R_kgDOJe0Zww
  category: Comment
  category-id: DIC_kwDOJe0Zw84CWQcl

# Plugins
plugins: [jekyll-paginate]
